# Generated by Django 5.2.6 on 2025-10-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
    ]
