# Generated by Django 5.2.6 on 2025-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='price',
        ),
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
