# Generated by Django 5.2.6 on 2025-10-02 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bike_created_at_remove_bike_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
