# Generated by Django 5.2.6 on 2025-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bike_created_at_bike_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
